// This file is generated. Do not edit this file!
import React from "react";

export type IconProps = {
  className?: string;
};
const Heart = (props: IconProps) => (
  <svg
    {...props}
    className={`fill-current ${props.className}`}
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="256"
    height="256"
    viewBox="0 0 256 256"
  >
    <path
      fill="currentColor"
      d="M240 94c0 70-103.79 126.66-108.21 129a8 8 0 0 1-7.58 0C119.79 220.66 16 164 16 94a62.07 62.07 0 0 1 62-62c20.65 0 38.73 8.88 50 23.89C139.27 40.88 157.35 32 178 32a62.07 62.07 0 0 1 62 62"
    />
  </svg>
);
const Money = (props: IconProps) => (
  <svg
    {...props}
    className={`fill-current ${props.className}`}
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="100"
    height="100"
    viewBox="0 0 100 100"
  >
    <path
      fill="currentColor"
      d="M54.284 44.798v-10.11c3.297.807 6.52 2.344 9.157 4.762l.011-.015c.197.157.436.265.708.265c.358 0 .665-.173.877-.428l.015.003l4.262-6.008l-.01-.005c.175-.202.291-.458.291-.746c0-.34-.153-.638-.387-.849c-3.953-3.651-9-5.843-14.924-6.502v-5.806h-.001c0-.637-.516-1.153-1.153-1.153h-4.578c-.637 0-1.153.516-1.153 1.153v5.659c-9.89 1.025-15.75 7.326-15.75 14.725c0 9.963 8.205 12.82 15.75 14.652v11.354c-4.845-.868-8.827-3.379-11.536-6.19c-.019-.021-.039-.039-.06-.058l-.052-.051l-.008.011a1.134 1.134 0 0 0-.719-.273a1.14 1.14 0 0 0-.998.608l-.014-.002l-4.125 6.124l.005.01a1.133 1.133 0 0 0-.292.748c0 .367.182.679.448.89l-.011.016c4.029 4.029 9.67 6.959 17.362 7.619v5.44c0 .637.516 1.153 1.153 1.153h4.578c.637 0 1.153-.517 1.153-1.153h.001V75.2c10.769-1.1 16.117-7.398 16.117-15.531c0-10.035-8.498-12.967-16.117-14.871m-6.886-1.686c-3.003-.951-5.055-2.051-5.055-4.176c0-2.49 1.832-4.248 5.055-4.688zm6.886 22.784V56.08c3.224 1.025 5.495 2.199 5.495 4.615c0 2.345-1.759 4.468-5.495 5.201"
    />
  </svg>
);
const Music = (props: IconProps) => (
  <svg
    {...props}
    className={`fill-current ${props.className}`}
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
  >
    <g fill="none">
      <circle
        cx="6"
        cy="18"
        r="3"
        fill="currentColor"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <circle
        cx="18"
        cy="17"
        r="3"
        fill="currentColor"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <path fill="currentColor" d="M21 3L9 6v4l12-3z" />
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 18v-8m12 7V7M9 10V6l12-3v4M9 10l12-3"
      />
    </g>
  </svg>
);
const Next = (props: IconProps) => (
  <svg
    {...props}
    className={`fill-current ${props.className}`}
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="32"
    height="32"
    viewBox="0 0 32 32"
  >
    <path
      fill="currentColor"
      d="M26.002 5a1 1 0 1 1 2 0v22a1 1 0 0 1-2 0zM3.999 6.504c0-2.002 2.236-3.192 3.897-2.073l14.003 9.432A2.5 2.5 0 0 1 21.912 18L7.909 27.56c-1.66 1.132-3.91-.056-3.91-2.065z"
    />
  </svg>
);
const Tank = (props: IconProps) => (
  <svg
    {...props}
    className={`fill-current ${props.className}`}
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
  >
    <path
      fill="currentColor"
      d="M20 12H4v-1h2l1-5h5l1 5h7zm-6.78-5l.4 2H22V7zM22 16a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3a3 3 0 0 1 3-3h14a3 3 0 0 1 3 3M6 16a1 1 0 0 0-1-1a1 1 0 0 0-1 1a1 1 0 0 0 1 1a1 1 0 0 0 1-1m7 0a1 1 0 0 0-1-1a1 1 0 0 0-1 1a1 1 0 0 0 1 1a1 1 0 0 0 1-1m7 0a1 1 0 0 0-1-1a1 1 0 0 0-1 1a1 1 0 0 0 1 1a1 1 0 0 0 1-1"
    />
  </svg>
);

export { Heart, Money, Music, Next, Tank };
